### ISSUE TITLE
Wyłączanie "Potwierdź swoje konto"

### ISSUE THREAD

**Issue by robsonek** [imper86/allegroapi#10]
Podczas autoryzacji wyświetla się opcjonalne okno potwierdzenia konta. Może warto też dodać to jako opcję a nie jako warunek? Jest to 'prompt' => 'confirm' w metodzie createAuthUrl

**Comment by imper86** [comment]
@robsonek dodałem parametr $prompt do metody createAuthUrl. Zostawiłem domyślnie jako "true" ze względu na (nazwijmy to) kompatybilność wsteczną.
