### ISSUE TITLE
composer

### ISSUE THREAD

**Issue by robsonek** [imper86/allegroapi#11]
Prośba o zaktualizowanie wersji w Composer

**Comment by imper86** [comment]
Możesz doprecyzować? Najnowsza wersja jest na packagist i composer powinien ją bez problemu pobierać.

**Comment by robsonek** [comment]
o teraz widzę ze są wszystkie. Przedtem pobierała się wersja z 2019 roku :)
            "name": "imper86/allegro-rest-api-sdk",
            "version": "v2.0.0",

**Comment by imper86** [comment]
imper86/allegro-rest-api-sdk to była takie eksperymentalne repozytorium, wszystko przerzuciłem do imper86/allegroapi. Jest kolejne eksperymentalne - https://github.com/imper86/php-allegro-api - prawdopodobnie też wyląduje tutaj jako wersja 6 :)

**Comment by dzafel** [comment]
Przydałoby się zaktualizować readme.me bo ciągle jest `composer require imper86/allegro-rest-api-sdk` a to pobiera wersję z 2019 roku, powinno być `composer require imper86/allegroapi` ;)

**Comment by imper86** [comment]
@dzafel poprawione, dzięki! :)
