### ISSUE TITLE
Guzzle 7 support

### ISSUE THREAD

**Issue by kamilkozak** [imper86/allegroapi#12]
Jest szansa żeby zaktualizować guzzle do v7 ?

**Comment by imper86** [comment]
W ramach aktualnej wersji nie ze względu na kompatybilność wsteczną. Rozważę kwestię, być może w nowej "major" wersji.
Tymczasem mogę zaproponować tą bibliotekę - https://github.com/imper86/php-allegro-api - która umożliwia (a nawet wręcz wymusza) użycie swojego klienta http, zgodnego z PSR-18 i fabryki zgodne z PSR-17.

**Comment by kamilkozak** [comment]
Wygląda całkiem dobrze. Nowe metody będą dodawane na bieżąco równolegle z tą biblioteką?

**Comment by imper86** [comment]
Tak, zawsze jak tylko dowiem się o nowych metodach to aktualizuję równolegle obydwie :)

**Comment by kamilkozak** [comment]
Podczas aktualizacji proszę też o podbicie ramsey/uuid do v4.
