### ISSUE TITLE
aktualizacja z v5 do v6

### ISSUE THREAD

**Issue by RG-1** [imper86/allegroapi#14]
Po aktualizacji do 6.0.1 mam problem z następującymi błędami:

dla `if ($tokenBundle->getAccessToken()->isExpired()) {` ...

`PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Lcobucci\JWT\Token\Plain::isExpired(), 0 passed in /home/*****.php on line 76 and exactly 1 expected in /home/*****/vendor/lcobucci/jwt/src/Token/Plain.php:77`

dla `$tokenBundle = $allegroAuth->fetchTokenFromRefresh($tokenBundle->getRefreshToken());`

`PHP Fatal error:  Uncaught Error: Object of class Lcobucci\JWT\Token\Plain could not be converted to string in /home/*****/vendor/imper86/allegroapi/src/AllegroAuth.php:169`

Czy metody getAccessToken, fetchTokenFromRefresh oraz getRefreshToken uległy jakiejś zmianie? Na pierwszy rzut oka to powinno działać.

-----
wersje:
- imper86/allegroapi 6.0.1              
- lcobucci/clock 2.0.0              
- lcobucci/jwt 4.2.1 
- -
- php 7.4

**Comment by imper86** [comment]
błąd jest dość oczywisty - metoda `\Lcobucci\JWT\Token::isExpired` wymaga argumentu w postaci obiektu `\DateTimeInterface` - trzeba tam po prostu wrzucić np `new \DateTimeImmutable()`
