### ISSUE TITLE
Nowe metody API

### ISSUE THREAD

**Issue by robsonek** [imper86/allegroapi#15]
Hej!

Jest szansa dodać nowe metody? Potrzebuje m.in. https://developer.allegro.pl/documentation/#operation/getParcelTrackingUsingGET

W bibliotece jest tylko stara metoda (już deprecated) umożliwiająca śledzenie tylko paczek Allegro (https://developer.allegro.pl/documentation/#operation/getAllegroParcelTrackingUsingGET)

Dzięki za Twoją prace!

**Comment by imper86** [comment]
Hej :)

A może chciałbyś podjąć się utworzenia pull requesta z tą nowością?

**Comment by robsonek** [comment]
dodałem na szybko tą jedną metodę :)

**Comment by imper86** [comment]
gotowe :)
