### ISSUE TITLE
Ilość

### ISSUE THREAD

**Issue by kamilkozak** [imper86/allegroapi#5]
Jak zmienie ilość za pomocą tej biblioteki?

**Comment by imper86** [comment]
Ilość czego chcesz zmienić? Chodzi Ci o ilość przedmiotów wystawionych w aukcji?

**Comment by kamilkozak** [comment]
Tak ilość przedmiotów na aukcji za pomocą RESTa. Chyba służy do tego zasób PUT /sale/offer-quantity-change-commands/{commandId} ale nie mogę tego u Ciebie znaleźć.

**Comment by imper86** [comment]
Faktycznie, nie było gotowych modeli requestów do tego zasobu, właśnie je dorobiłem.
Nowe klasy znajdziesz tutaj: https://github.com/imper86/allegroapi/tree/master/src/Imper86/AllegroApi/Rest/Model/Request/OfferManagement/OfferQuantityChangeCommands

Jeśli ogarniasz konstrukcję innych requestów, to te raczej nie wymagają wyjaśniania.

Swoją drogą, ilość w aukcji można też zmienić zasobem PUT /sale/offers/{offerId}, tylko trzeba sobie wcześniej ściągnąć GETem na tym samym zasobie aktualne dane.

Mam nadzieję, że pomogłem.

**Comment by kamilkozak** [comment]
Pomogłeś nawet bardzo. Dziękuje i doceniam.

**Comment by imper86** [comment]
No to zamykam :)
