### ISSUE TITLE
fetchTokenFromRefresh - bad response

### ISSUE THREAD

**Issue by kamilkozak** [imper86/allegroapi#6]
Właśnie przechodzę na nową wersję 5 i trafiłem na problem z którym nie mogę sobie poradzić. Odświeżam token jak w dokumentacji:

`if ($tokenBundle->getAccessToken()->isExpired()) {
    $tokenBundle = $allegroAuth->fetchTokenFromRefresh($tokenBundle->getRefreshToken());
}`

i dostaję błąd 
`Bad response {"userId":1,"exception":"[object] (GuzzleHttp\\Exception\\BadResponseException(code: 400): Bad response at C:\\laragon\\www\\test\\vendor\\imper86\\allegro-rest-api-sdk\\src\\AllegroAuth.php:117)`

Reszta wydaje się działać bez problemów. Masz jakiś pomysł czym to może być spowodowane?

**Comment by imper86** [comment]
Szczerze mówiąc nie, przed chwilą przetestowałem u siebie i działa bez problemów. Złap ten wyjątek, który rzuca ta metoda (BadResponseException). Masz tam metody getRequest() i getResponse(). Jak wywołasz (string)$exception->getResponse()->getBody() to będziesz miał pełny opis odpowiedzi od allegro. Daj znać co tam miałeś.

**Comment by kamilkozak** [comment]
Dziś wszystko ruszyło. To musiał być problem po stronie allegro. Dzięki za zainteresowanie.
