### ISSUE TITLE
PUT /order/checkout-forms/{checkoutForm.id}/fulfillment

### ISSUE THREAD

**Issue by kamilkozak** [imper86/allegroapi#7]
Bardzo proszę o dodanie zasobu: `PUT /order/checkout-forms/{checkoutForm.id}/fulfillment` do zmiany statusu realizacji zamówienia.

Link w dokumentacji [https://developer.allegro.pl/documentation/#operation/setOrderFulfillmentUsingPUT](url)

**Comment by imper86** [comment]
@kamilkozak zrobione

**Comment by kamilkozak** [comment]
Coś pięknego. Po raz kolejny dziękuje.
